In [1]:
import numpy as np

In [11]:
N = int(input("Введите число "))

first = np.arange(0, N)
res = np.flip(first,0)
print(first)
print(res)

Введите число 15
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]
[14 13 12 11 10  9  8  7  6  5  4  3  2  1  0]


In [20]:
N = int(input("Введите число "))

first = np.arange(0, N)
res = np.flip(first,0)

matrix = np.diag(res)

print(f"Сумма значение по диагонали: {sum(np.diagonal(matrix))}")

Введите число 11
Сумма значение по диагонали: 55


In [24]:
a = np.array([[4, 2, 1], [1, 3, 0], [0, 5, 4]])
b = np.array([4, 12, -3])

from numpy import linalg

np.around(linalg.solve(a, b), decimals = 2)

array([ 0.47,  3.84, -5.56])

In [29]:
users_stats = np.array(
    [
        [2, 1, 0, 0, 0, 0],
        [1, 1, 2, 1, 0, 0],
        [2, 0, 1, 0, 0, 0],
        [1, 1, 2, 1, 0, 1],
        [0, 0, 1, 2, 0, 0],
        [0, 0, 0, 0, 0, 5],
        [1, 0, 0, 0, 0, 0],
        [0, 1, 1, 0, 0, 0],
        [0, 0, 0, 1, 1, 3],
        [1, 0, 0, 2, 1, 4]
    ]
)



In [61]:
next_user_stats = np.array([0, 1, 2, 0, 0, 0])
next_Length = np.linalg.norm(next_user_stats)

similarity = []
for i in range(0, 10):
    
    iLength = np.linalg.norm(users_stats[i, :])
    res = round(np.dot( users_stats[i, :], next_user_stats) / (iLength  * next_Length), 2)
    similarity.append(res)
    
a = similarity.index(max(similarity)) + 1    
print(f"самый похожий пользователь - {a} ")





самый похожий пользователь - 8 
